
# Update these links soon!
contact_links:
  - name: BillHertzing Community Support
    url: https://gitter.im/BillHertzing/BillHertzing
    about: Please ask and answer questions here.
#  - name: Security Bug Bounty
#    url: https://bounty.github.com/
#    about: Please report security vulnerabilities here.
    